INSERT INTO M_ROLE_USER(ROLE_ID,ROLE_NAME,ROLE_DESC) VALUES ('1','Customer','Customer');
INSERT INTO M_ROLE_USER(ROLE_ID,ROLE_NAME,ROLE_DESC) VALUES ('2','Employee','Employee');
INSERT INTO M_ROLE_USER(ROLE_ID,ROLE_NAME,ROLE_DESC) VALUES ('3','Agent','Agent');
INSERT INTO M_ROLE_USER(ROLE_ID,ROLE_NAME,ROLE_DESC) VALUES ('4','Admin','Admin');

INSERT INTO M_CUSTOMER(CUST_ID,ADDRESS,CUST_NAME,CUST_PHONE,ROLE_ID,CUST_PWD) VALUES('101','Bhubaneswar','Chiranjibee1','9090','1','chiranjibee');
INSERT INTO M_CUSTOMER(CUST_ID,ADDRESS,CUST_NAME,CUST_PHONE,ROLE_ID,CUST_PWD) VALUES('102','Bhubaneswar','Chiranjibee2','9090','2','chiranjibee');
INSERT INTO M_CUSTOMER(CUST_ID,ADDRESS,CUST_NAME,CUST_PHONE,ROLE_ID,CUST_PWD) VALUES('103','Bhubaneswar','Chiranjibee3','9090','3','chiranjibee');
INSERT INTO M_CUSTOMER(CUST_ID,ADDRESS,CUST_NAME,CUST_PHONE,ROLE_ID,CUST_PWD) VALUES('104','Bhubaneswar','Chiranjibee4','9090','4','chiranjibee');
INSERT INTO M_CUSTOMER(CUST_ID,ADDRESS,CUST_NAME,CUST_PHONE,ROLE_ID,CUST_PWD) VALUES('105','Bhubaneswar','Chiranjibee5','9090','1','chiranjibee');
INSERT INTO M_CUSTOMER(CUST_ID,ADDRESS,CUST_NAME,CUST_PHONE,ROLE_ID,CUST_PWD) VALUES('106','Bhubaneswar','Chiranjibee6','9090','2','chiranjibee');
INSERT INTO M_CUSTOMER(CUST_ID,ADDRESS,CUST_NAME,CUST_PHONE,ROLE_ID,CUST_PWD) VALUES('107','Bhubaneswar','Chiranjibee7','9090','3','chiranjibee');
INSERT INTO M_CUSTOMER(CUST_ID,ADDRESS,CUST_NAME,CUST_PHONE,ROLE_ID,CUST_PWD) VALUES('108','Bhubaneswar','Chiranjibee8','9090','1','chiranjibee');
INSERT INTO M_CUSTOMER(CUST_ID,ADDRESS,CUST_NAME,CUST_PHONE,ROLE_ID,CUST_PWD) VALUES('109','Bhubaneswar','Chiranjibee9','9090','3','chiranjibee');
INSERT INTO M_CUSTOMER(CUST_ID,ADDRESS,CUST_NAME,CUST_PHONE,ROLE_ID,CUST_PWD) VALUES('110','Bhubaneswar','Chiranjibee10','9090','2','chiranjibee');

