INSERT INTO M_PAYMENT_TYPE  VALUES (10001,'CASH');
INSERT INTO M_PAYMENT_TYPE  VALUES (10002,'CARD');
INSERT INTO M_PAYMENT_TYPE  VALUES (10003,'WALLET');
INSERT INTO M_PAYMENT_TYPE  VALUES (10004,'NETBANKING');